#!/bin/bash
set -e
set -o pipefail

if [ $(uname -a | grep -ci Ubuntu) -ge 1 ]; then
    sudo modprobe mpls-router mpls-iptunnel vrf
fi

# Run foundational frr daemons in background
sudo zebra &
sleep 2
sudo mgmtd &
sleep 2

# Run protocol-specific daemons in background
sudo ospfd &
sleep 2
sudo ldpd &
sleep 2

# Boot up vtysh
sudo vtysh -b

while true ; do sleep 365d ; done
